services:
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000/

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/Employee-Management-System

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local